import '../styles/globals.css';
import { Inter } from 'next/font/google';
import { Button } from '@rethinking-siakad/ui';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  title: 'SIAKAD Web',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <head />
      <body className="flex min-h-screen flex-col bg-background font-sans antialiased">
        <Button variant="secondary">Hello ther</Button>
        {children}
      </body>
    </html>
  );
}
